// 此文件由 generate-test-config.ts 自动生成，请勿手动编辑
// 此文件包含所有 .spect.html 测试文件和示例的配置信息

export interface TestInfo
{
    name: string;
    description: string;
    htmlFile: string;
    testName: string;
    dirPath: string; // 目录路径（相对于根目录）
    type: 'spectest' | 'example'; // 测试类型
}

export const tests: TestInfo[] = [
    {
        'name': 'WebGPU 深度附件和画布颜色读取测试',
        'description': '测试深度附件的正确性以及从画布读取像素颜色的功能。包含两个测试用例：没有深度附件时深度测试被禁用，有深度附件时深度测试启用。',
        'htmlFile': './src/tests/depth-attachment-canvas-readpixels.spect.html',
        'testName': 'depth-attachment-canvas-readpixels',
        'dirPath': 'src/tests',
        'type': 'spectest',
    },
    {
        'name': 'RenderObjectChanges',
        'description': '测试 示例',
        'htmlFile': './src/webgpu/RenderObjectChanges/index.html',
        'testName': 'example-RenderObjectChanges',
        'dirPath': '测试',
        'type': 'example',
    },
    {
        'name': 'sky',
        'description': '测试 示例',
        'htmlFile': './src/webgpu/sky/index.html',
        'testName': 'example-sky',
        'dirPath': '测试',
        'type': 'example',
    },
    {
        'name': 'helloTriangle',
        'description': 'Basic Graphics 示例',
        'htmlFile': './src/webgpu/helloTriangle/index.html',
        'testName': 'example-helloTriangle',
        'dirPath': 'Basic Graphics',
        'type': 'example',
    },
    {
        'name': 'helloTriangleMSAA',
        'description': 'Basic Graphics 示例',
        'htmlFile': './src/webgpu/helloTriangleMSAA/index.html',
        'testName': 'example-helloTriangleMSAA',
        'dirPath': 'Basic Graphics',
        'type': 'example',
    },
    {
        'name': 'rotatingCube',
        'description': 'Basic Graphics 示例',
        'htmlFile': './src/webgpu/rotatingCube/index.html',
        'testName': 'example-rotatingCube',
        'dirPath': 'Basic Graphics',
        'type': 'example',
    },
    {
        'name': 'twoCubes',
        'description': 'Basic Graphics 示例',
        'htmlFile': './src/webgpu/twoCubes/index.html',
        'testName': 'example-twoCubes',
        'dirPath': 'Basic Graphics',
        'type': 'example',
    },
    {
        'name': 'texturedCube',
        'description': 'Basic Graphics 示例',
        'htmlFile': './src/webgpu/texturedCube/index.html',
        'testName': 'example-texturedCube',
        'dirPath': 'Basic Graphics',
        'type': 'example',
    },
    {
        'name': 'instancedCube',
        'description': 'Basic Graphics 示例',
        'htmlFile': './src/webgpu/instancedCube/index.html',
        'testName': 'example-instancedCube',
        'dirPath': 'Basic Graphics',
        'type': 'example',
    },
    {
        'name': 'fractalCube',
        'description': 'Basic Graphics 示例',
        'htmlFile': './src/webgpu/fractalCube/index.html',
        'testName': 'example-fractalCube',
        'dirPath': 'Basic Graphics',
        'type': 'example',
    },
    {
        'name': 'cubemap',
        'description': 'Basic Graphics 示例',
        'htmlFile': './src/webgpu/cubemap/index.html',
        'testName': 'example-cubemap',
        'dirPath': 'Basic Graphics',
        'type': 'example',
    },
    {
        'name': 'reversedZ',
        'description': 'WebGPU Features 示例',
        'htmlFile': './src/webgpu/reversedZ/index.html',
        'testName': 'example-reversedZ',
        'dirPath': 'WebGPU Features',
        'type': 'example',
    },
    {
        'name': 'renderBundles',
        'description': 'WebGPU Features 示例',
        'htmlFile': './src/webgpu/renderBundles/index.html',
        'testName': 'example-renderBundles',
        'dirPath': 'WebGPU Features',
        'type': 'example',
    },
    {
        'name': 'occlusionQuery',
        'description': 'WebGPU Features 示例',
        'htmlFile': './src/webgpu/occlusionQuery/index.html',
        'testName': 'example-occlusionQuery',
        'dirPath': 'WebGPU Features',
        'type': 'example',
    },
    {
        'name': 'samplerParameters',
        'description': 'WebGPU Features 示例',
        'htmlFile': './src/webgpu/samplerParameters/index.html',
        'testName': 'example-samplerParameters',
        'dirPath': 'WebGPU Features',
        'type': 'example',
    },
    {
        'name': 'timestampQuery',
        'description': 'WebGPU Features 示例',
        'htmlFile': './src/webgpu/timestampQuery/index.html',
        'testName': 'example-timestampQuery',
        'dirPath': 'WebGPU Features',
        'type': 'example',
    },
    {
        'name': 'blending',
        'description': 'WebGPU Features 示例',
        'htmlFile': './src/webgpu/blending/index.html',
        'testName': 'example-blending',
        'dirPath': 'WebGPU Features',
        'type': 'example',
    },
    {
        'name': 'computeBoids',
        'description': 'GPGPU Demos 示例',
        'htmlFile': './src/webgpu/computeBoids/index.html',
        'testName': 'example-computeBoids',
        'dirPath': 'GPGPU Demos',
        'type': 'example',
    },
    {
        'name': 'gameOfLife',
        'description': 'GPGPU Demos 示例',
        'htmlFile': './src/webgpu/gameOfLife/index.html',
        'testName': 'example-gameOfLife',
        'dirPath': 'GPGPU Demos',
        'type': 'example',
    },
    {
        'name': 'bitonicSort',
        'description': 'GPGPU Demos 示例',
        'htmlFile': './src/webgpu/bitonicSort/index.html',
        'testName': 'example-bitonicSort',
        'dirPath': 'GPGPU Demos',
        'type': 'example',
    },
    {
        'name': 'cameras',
        'description': 'Graphics Techniques 示例',
        'htmlFile': './src/webgpu/cameras/index.html',
        'testName': 'example-cameras',
        'dirPath': 'Graphics Techniques',
        'type': 'example',
    },
    {
        'name': 'normalMap',
        'description': 'Graphics Techniques 示例',
        'htmlFile': './src/webgpu/normalMap/index.html',
        'testName': 'example-normalMap',
        'dirPath': 'Graphics Techniques',
        'type': 'example',
    },
    {
        'name': 'shadowMapping',
        'description': 'Graphics Techniques 示例',
        'htmlFile': './src/webgpu/shadowMapping/index.html',
        'testName': 'example-shadowMapping',
        'dirPath': 'Graphics Techniques',
        'type': 'example',
    },
    {
        'name': 'deferredRendering',
        'description': 'Graphics Techniques 示例',
        'htmlFile': './src/webgpu/deferredRendering/index.html',
        'testName': 'example-deferredRendering',
        'dirPath': 'Graphics Techniques',
        'type': 'example',
    },
    {
        'name': 'particles',
        'description': 'Graphics Techniques 示例',
        'htmlFile': './src/webgpu/particles/index.html',
        'testName': 'example-particles',
        'dirPath': 'Graphics Techniques',
        'type': 'example',
    },
    {
        'name': 'points',
        'description': 'Graphics Techniques 示例',
        'htmlFile': './src/webgpu/points/index.html',
        'testName': 'example-points',
        'dirPath': 'Graphics Techniques',
        'type': 'example',
    },
    {
        'name': 'imageBlur',
        'description': 'Graphics Techniques 示例',
        'htmlFile': './src/webgpu/imageBlur/index.html',
        'testName': 'example-imageBlur',
        'dirPath': 'Graphics Techniques',
        'type': 'example',
    },
    {
        'name': 'cornell',
        'description': 'Graphics Techniques 示例',
        'htmlFile': './src/webgpu/cornell/index.html',
        'testName': 'example-cornell',
        'dirPath': 'Graphics Techniques',
        'type': 'example',
    },
    {
        'name': 'a-buffer',
        'description': 'Graphics Techniques 示例',
        'htmlFile': './src/webgpu/a-buffer/index.html',
        'testName': 'example-a-buffer',
        'dirPath': 'Graphics Techniques',
        'type': 'example',
    },
    {
        'name': 'skinnedMesh',
        'description': 'Graphics Techniques 示例',
        'htmlFile': './src/webgpu/skinnedMesh/index.html',
        'testName': 'example-skinnedMesh',
        'dirPath': 'Graphics Techniques',
        'type': 'example',
    },
    {
        'name': 'textRenderingMsdf',
        'description': 'Graphics Techniques 示例',
        'htmlFile': './src/webgpu/textRenderingMsdf/index.html',
        'testName': 'example-textRenderingMsdf',
        'dirPath': 'Graphics Techniques',
        'type': 'example',
    },
    {
        'name': 'volumeRenderingTexture3D',
        'description': 'Graphics Techniques 示例',
        'htmlFile': './src/webgpu/volumeRenderingTexture3D/index.html',
        'testName': 'example-volumeRenderingTexture3D',
        'dirPath': 'Graphics Techniques',
        'type': 'example',
    },
    {
        'name': 'wireframe',
        'description': 'Graphics Techniques 示例',
        'htmlFile': './src/webgpu/wireframe/index.html',
        'testName': 'example-wireframe',
        'dirPath': 'Graphics Techniques',
        'type': 'example',
    },
    {
        'name': 'resizeCanvas',
        'description': 'Web Platform Integration 示例',
        'htmlFile': './src/webgpu/resizeCanvas/index.html',
        'testName': 'example-resizeCanvas',
        'dirPath': 'Web Platform Integration',
        'type': 'example',
    },
    {
        'name': 'resizeObserverHDDPI',
        'description': 'Web Platform Integration 示例',
        'htmlFile': './src/webgpu/resizeObserverHDDPI/index.html',
        'testName': 'example-resizeObserverHDDPI',
        'dirPath': 'Web Platform Integration',
        'type': 'example',
    },
    {
        'name': 'transparentCanvas',
        'description': 'Web Platform Integration 示例',
        'htmlFile': './src/webgpu/transparentCanvas/index.html',
        'testName': 'example-transparentCanvas',
        'dirPath': 'Web Platform Integration',
        'type': 'example',
    },
    {
        'name': 'multipleCanvases',
        'description': 'Web Platform Integration 示例',
        'htmlFile': './src/webgpu/multipleCanvases/index.html',
        'testName': 'example-multipleCanvases',
        'dirPath': 'Web Platform Integration',
        'type': 'example',
    },
    {
        'name': 'videoUploading',
        'description': 'Web Platform Integration 示例',
        'htmlFile': './src/webgpu/videoUploading/index.html',
        'testName': 'example-videoUploading',
        'dirPath': 'Web Platform Integration',
        'type': 'example',
    },
    {
        'name': 'worker',
        'description': 'Web Platform Integration 示例',
        'htmlFile': './src/webgpu/worker/index.html',
        'testName': 'example-worker',
        'dirPath': 'Web Platform Integration',
        'type': 'example',
    },
    {
        'name': 'animometer',
        'description': 'Benchmarks 示例',
        'htmlFile': './src/webgpu/animometer/index.html',
        'testName': 'example-animometer',
        'dirPath': 'Benchmarks',
        'type': 'example',
    },
];
