name: Master Branch CI

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'

    - name: Install dependencies
      run: npm install

    - name: Run unit tests
      run: npm test

    - name: Build project
      run: npm run build

    - name: docs
      run: npm run docs

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public

    - name: Check npm version
      id: check-npm-version
      run: |
        CURRENT_VERSION=$(node -p "require('./package.json').version")
        PUBLISHED_VERSION=$(npm view . version 2>/dev/null || echo "0.0.0")
        if [ "$CURRENT_VERSION" != "$PUBLISHED_VERSION" ]; then
          echo "publish=true" >> $GITHUB_OUTPUT
        else
          echo "publish=false" >> $GITHUB_OUTPUT
        fi

    - name: Publish to npm
      if: steps.check-npm-version.outputs.publish == 'true'
      run: |
        echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc
        npm run release

    - name: Create git tag
      if: steps.check-npm-version.outputs.publish == 'true'
      run: |
        VERSION=$(node -p "require('./package.json').version")
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git tag -a v$VERSION -m "Release v$VERSION"
        git push origin v$VERSION
